### ISSUE TITLE
Csync2 not syncing files included in the conf folder

### ISSUE THREAD

**Issue by andreapernici** [rvanlaar/csync2#1]
I followed all the easy conf step found in the paper, but even if the csync2 looks working no file are synced.

Do you know what can be the issue?

My conf is very simple and include 2 hosts.

Just to give some hint when I try the sync with csync2 -xv I get

```
Connection closed.
Finished with 0 errors.
```

But no file are synced.

**Comment by rvanlaar** [comment]
Hi Andrea, 

Thank you for reaching out. I'm not sure what the error is. Csync2 can be tricky to get the hang of at first.
There is a specific mailing-list for questions regarding csync2. 

csync2@lists.linbit.com

Regards,

Roland van Laar
